
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 31 10:59:45 EST 2013
//----------------------------------------------------

package smpl.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 26;
  public static final int BIT_COMP = 22;
  public static final int LBRACKET = 2;
  public static final int HEX_CHARACTER = 62;
  public static final int MULT = 17;
  public static final int PAIR_QS = 37;
  public static final int LTEQ = 27;
  public static final int CONCAT = 32;
  public static final int BIT_AND = 20;
  public static final int CASE = 52;
  public static final int CAR = 38;
  public static final int DOUBLE = 65;
  public static final int INTEGER = 64;
  public static final int CDR = 39;
  public static final int LPAREN = 6;
  public static final int LVBRACKET = 4;
  public static final int REF = 59;
  public static final int MINUS = 16;
  public static final int CHARACTER = 61;
  public static final int RPAREN = 7;
  public static final int EMPTY_LIST = 35;
  public static final int LT = 25;
  public static final int LAZY = 46;
  public static final int COMMA = 12;
  public static final int CALL = 45;
  public static final int LOGIC_NOT = 31;
  public static final int LOGIC_AND = 29;
  public static final int DIV = 18;
  public static final int PLUS = 15;
  public static final int IF = 49;
  public static final int ASSIGN = 13;
  public static final int DOT = 14;
  public static final int EOF = 0;
  public static final int RBRACKET = 3;
  public static final int SIZE = 40;
  public static final int TRUE = 33;
  public static final int error = 1;
  public static final int SEMI_COLON = 11;
  public static final int MOD = 19;
  public static final int PAIR = 36;
  public static final int EQ = 23;
  public static final int PRINT_LN = 54;
  public static final int EQV = 41;
  public static final int LOGIC_OR = 30;
  public static final int COLON = 10;
  public static final int READ_INT = 56;
  public static final int ELSE = 51;
  public static final int LBRACE = 8;
  public static final int BE = 57;
  public static final int READ = 55;
  public static final int NOT_EQ = 28;
  public static final int SUBSTR = 43;
  public static final int RVBRACKET = 5;
  public static final int LET = 47;
  public static final int THEN = 50;
  public static final int RBRACE = 9;
  public static final int STRING = 60;
  public static final int PROC = 44;
  public static final int DEF = 48;
  public static final int BIT_OR = 21;
  public static final int FALSE = 34;
  public static final int GT = 24;
  public static final int EQ_COMPARE = 42;
  public static final int PRINT = 53;
  public static final int IDENTIFIER = 63;
  public static final int DYNAMIC = 58;
}

