
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 28 20:16:39 EST 2012
//----------------------------------------------------

package smpl.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int KW_READ_INT = 48;
  public static final int LIT_COLON = 10;
  public static final int KW_FALSE = 34;
  public static final int KW_DYNAMIC = 50;
  public static final int HEX_CHARACTER = 54;
  public static final int KW_PRINT = 45;
  public static final int LIT_ASSIGN = 13;
  public static final int KW_REF = 51;
  public static final int DOUBLE = 57;
  public static final int INTEGER = 56;
  public static final int LIT_MULTIPLY = 17;
  public static final int LIT_LVBRACKET = 4;
  public static final int KW_EMPTY_LIST = 35;
  public static final int KW_CASE = 44;
  public static final int LIT_RBRACKET = 3;
  public static final int CHARACTER = 53;
  public static final int LIT_REL_GT = 24;
  public static final int LIT_DOT = 14;
  public static final int LIT_LOGIC_NOT = 31;
  public static final int LIT_LOGIC_AND = 29;
  public static final int LIT_LBRACE = 8;
  public static final int LIT_MODULUS = 19;
  public static final int LIT_LOGIC_OR = 30;
  public static final int LIT_ADD = 15;
  public static final int KW_LAZY = 38;
  public static final int KW_CALL = 37;
  public static final int EOF = 0;
  public static final int LIT_RBRACE = 9;
  public static final int error = 1;
  public static final int LIT_MINUS = 16;
  public static final int LIT_REL_GTEQ = 26;
  public static final int LIT_BIT_OR = 21;
  public static final int KW_TRUE = 33;
  public static final int KW_IF = 41;
  public static final int LIT_REL_LTEQ = 27;
  public static final int LIT_REL_LT = 25;
  public static final int KW_LET = 39;
  public static final int LIT_COMMA = 12;
  public static final int LIT_REL_NOT_EQ = 28;
  public static final int LIT_DIVIDE = 18;
  public static final int LIT_BIT_AND = 20;
  public static final int KW_DEF = 40;
  public static final int LIT_LBRACKET = 2;
  public static final int LIT_RVBRACKET = 5;
  public static final int LIT_CONCAT = 32;
  public static final int KW_ELSE = 43;
  public static final int LIT_BIT_COMP = 22;
  public static final int KW_READ = 47;
  public static final int STRING = 52;
  public static final int LIT_LPAREN = 6;
  public static final int LIT_SEMI_COLON = 11;
  public static final int KW_THEN = 42;
  public static final int KW_BE = 49;
  public static final int KW_PRINT_LN = 46;
  public static final int KW_PROC = 36;
  public static final int LIT_REL_EQ = 23;
  public static final int LIT_RPAREN = 7;
  public static final int IDENTIFIER = 55;
}

